### ISSUE TITLE
ts-pip-plugin doesn't support TrustSource API version 2

### ISSUE THREAD

**Issue by JoeMabor** [TrustSource/ts-pip-plugin#1]
It seems this library is not maintained anymore and since it not compatitable with TrustSource API version 2, I created new tool [TrustSource-pip-scan](https://github.com/JoeMabor/TrustSource-pip-scan) which supports API version 2 and also add evaluation of TrustSource analysis results(useful in CI/CD pipelines)

**Comment by jthDEV** [comment]
Hi Joe, yes, your observation is correct. Due to several reasons - user comfort, maintenance efforts, etc. - we decided to merge the different scanners stepwise into one. Our new swiss-army-knife for scanning is called [ts-scan](https://github.com/trustsource/ts-scan) and can be found in the corresponding repository. Python has been moved as one of the first languages. We will indicate this accordingly in the repo. Thanks for the hint.
